#!/usr/bin/env python3
"""Start the next revision by copying the newest one's working set.

Each rev<N>/ folder is self-contained: the manuscript, figs/ and the response
letter all live there (the bibliography is shared, at the repository root), so a revision can always be rebuilt exactly
as it was submitted. Starting rev<N+1> therefore means copying those sources
forward and leaving the previous revision frozen.

Only sources are copied. The previous revision's deliverables (its submitted
PDFs, cover letter .docx, submission/ directory) stay behind, because they
belong to that revision. The clean manuscript is not copied either: it is not a
source, it is generated by scripts/make_submission.py.

Usage:
    python3 scripts/new_revision.py           # newest rev<N> -> rev<N+1>
    python3 scripts/new_revision.py --from rev1 --to rev3
    python3 scripts/new_revision.py --dry-run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Copied forward: the sources the next revision is written from.
SOURCE_FILES = (
    "manuscript_annotated.tex",
    "manuscript.tex",
    "response_to_reviewers.tex",
)
SOURCE_DIRS = ("figs",)


def rev_dirs() -> list[tuple[int, Path]]:
    return sorted(
        (int(p.name[3:]), p)
        for p in REPO.glob("rev[0-9]*")
        if p.is_dir()
        and p.name[3:].isdigit()
        and any((p / n).exists() for n in ("manuscript_annotated.tex", "manuscript.tex"))
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--from", dest="src", type=Path, default=None, help="source revision (default: newest)")
    ap.add_argument("--to", dest="dst", type=Path, default=None, help="target revision (default: next number)")
    ap.add_argument("--dry-run", action="store_true", help="list what would be copied")
    args = ap.parse_args()

    revs = rev_dirs()
    if args.src is not None:
        src = args.src if args.src.is_absolute() else REPO / args.src
    elif revs:
        src = revs[-1][1]
    else:
        ap.error("no rev<N> with a manuscript found; pass --from explicitly")

    if args.dst is not None:
        dst = args.dst if args.dst.is_absolute() else REPO / args.dst
    else:
        n = max((num for num, _ in revs), default=-1) + 1
        dst = REPO / f"rev{n}"

    if not src.is_dir():
        ap.error(f"{src} is not a directory")
    if dst.exists():
        ap.error(f"{dst} already exists; delete it or pass a different --to")

    planned: list[tuple[Path, Path]] = []
    for name in SOURCE_FILES:
        if (src / name).exists():
            planned.append((src / name, dst / name))
    for name in SOURCE_DIRS:
        for p in sorted((src / name).rglob("*")):
            if p.is_file() and not p.name.startswith("."):
                planned.append((p, dst / p.relative_to(src)))

    print(f"{src.name} -> {dst.name}")
    for s, d in planned:
        print(f"  {d.relative_to(REPO)}")
    if args.dry_run:
        print(f"({len(planned)} files, dry run -- nothing written)")
        return 0

    for s, d in planned:
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)

    manuscript = next((n for n in SOURCE_FILES if n.startswith("manuscript") and (dst / n).exists()), "manuscript.tex")
    print(f"\ncopied {len(planned)} files. Next steps:")
    print(f"  1. edit {dst.name}/{manuscript} -- accept or reset the previous")
    print("     round's tracked changes, then mark up the new round")
    if manuscript == "manuscript.tex":
        print(f"     (rename it to manuscript_annotated.tex and load the changes package")
        print("      once this round starts carrying tracked changes)")
    print(f"  2. rewrite {dst.name}/response_to_reviewers.tex for the new comments")
    print(f"  3. uv run scripts/make_submission.py {dst.name}")
    print(f"  4. git add {dst.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
