#!/usr/bin/env python3
"""Open the next stage of the paper by copying the current one's sources forward.

A paper moves through manuscript/ -> revision_1/ -> revision_2/ and so on, one
folder per round of review. Each folder is self-contained: the
manuscript, figs/ and the response letter all live there (the bibliography is
shared, at the repository root), so any stage can be rebuilt exactly as it was
sent.

Called with no arguments this advances one stage from the newest one, leaving it
frozen. Only sources are copied: the previous stage keeps its own deliverables and
its submission/ directory, and the clean manuscript is not copied at all, because
it is generated by scripts/prepare_submission.py rather than edited.

From the second revision onwards the previous round's tracked changes are accepted
in the copied manuscript, so the new round is marked up against the text the
reviewers have just seen rather than on top of the last round's markup. The
`\\linelabel` anchors survive, because the response letter points at them. Pass
--no-accept-previous to carry the markup over untouched.

Usage:
    python3 scripts/new_revision.py                     # newest stage -> next
    python3 scripts/new_revision.py --dry-run
    python3 scripts/new_revision.py --from manuscript --to revision_1
    python3 scripts/new_revision.py --no-accept-previous
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import prepare_submission as ps  # noqa: E402  (same directory, shared helpers)

REPO = Path(__file__).resolve().parent.parent

# Copied forward: the sources the next stage is written from.
SOURCE_FILES = (
    "manuscript_annotated.tex",
    "manuscript.tex",
    "response_to_reviewers.tex",
)
SOURCE_DIRS = ("figs",)

STAGE_MANUSCRIPT = "manuscript"
REVISION_PREFIX = "revision_"

ASSETS = Path(__file__).resolve().parent / "assets"

# Stands in the template letter where its title block belongs, until the manuscript's
# own is copied over it.
METADATA_MARKER = "%%PAPER-METADATA%%"

# Macro -> which argument survives, in the shape ps.flatten expects. Deliberately
# not ps.FLATTEN_CLEAN: that one also drops \linelabel and unwraps \hl, and here
# the anchors the response letter points at, along with the internal
# highlighting, have to reach the next round intact.
ACCEPT_MACROS = {"replaced": 0, "added": 0, "deleted": None}
TRACKED_CHANGE = re.compile(r"\\(" + "|".join(ACCEPT_MACROS) + r")(?![a-zA-Z])")

# Loaded into the manuscript the first time it becomes a revision. xcolor is
# already in the preamble, which \setdeletedmarkup needs.
CHANGES_PREAMBLE = r"""
% Tracked changes for the revision (see https://ctan.org/pkg/changes).
% This file is the annotated version, so the changes stay visible. The clean
% version is produced by scripts/prepare_submission.py, which accepts them.
\usepackage{changes}
\definechangesauthor[color=blue]{R1}
% ulem-based underline/strikeout breaks around superscript \cite, so use plain markup
\setaddedmarkup{#1}
\setdeletedmarkup{\textcolor{gray}{[deleted: #1]}}

"""


def paper_metadata(manuscript: str) -> str:
    """The response letter's title block, built from the manuscript's own.

    The authors and their affiliations belong in the manuscript, where an author
    looks for them. Typing them a second time into the letter is how the two drift
    apart, so they are read from there and written in once, when the letter is
    created. Correct them in the letter directly if they change afterwards.
    """
    title = ""
    m = re.search(r"\\title\s*\{", manuscript)
    if m is not None:
        body = manuscript[m.end() : ps.match_brace(manuscript, m.end() - 1) - 1]
        # \title{\bfseries The Title} -- the styling is the manuscript's, and the
        # letter sets its own, so only the words carry over.
        title = " ".join(re.sub(r"\\[a-zA-Z]+\s*", " ", body).split())

    block = [
        line
        for line in manuscript.split("\n")
        if re.match(r"\s*\\(author|affil)\b", line)
        or r"\renewcommand\Affilfont" in line
        or r"\renewcommand{\Affilfont}" in line
    ]
    return "\n".join(
        [
            r"\title{ \bfseries Response to Reviewers\\[0.4em]",
            f"\\large Manuscript: ``{title}''}}",
            "",
            *block,
        ]
    )


def has_manuscript(p: Path) -> bool:
    return any((p / n).exists() for n in ("manuscript_annotated.tex", "manuscript.tex"))


def revision_number(name: str) -> int | None:
    suffix = name[len(REVISION_PREFIX) :]
    return int(suffix) if name.startswith(REVISION_PREFIX) and suffix.isdigit() else None


def stage_dirs() -> list[Path]:
    """Every stage holding a manuscript, in the order the paper passes through them."""
    first = REPO / STAGE_MANUSCRIPT
    stages = [first] if first.is_dir() and has_manuscript(first) else []
    revisions = sorted(
        (n, p)
        for p in REPO.glob(f"{REVISION_PREFIX}*")
        if p.is_dir() and (n := revision_number(p.name)) is not None and has_manuscript(p)
    )
    return stages + [p for _, p in revisions]


def next_stage(src: Path) -> Path | None:
    """The folder that follows src in the pipeline."""
    if src.name == STAGE_MANUSCRIPT:
        return REPO / f"{REVISION_PREFIX}1"
    n = revision_number(src.name)
    return REPO / f"{REVISION_PREFIX}{n + 1}" if n is not None else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--from", dest="src", type=Path, default=None, help="stage to copy from (default: newest)")
    ap.add_argument("--to", dest="dst", type=Path, default=None, help="stage to create (default: the next one)")
    ap.add_argument("--dry-run", action="store_true", help="list what would be copied")
    ap.add_argument(
        "--accept-previous",
        action=argparse.BooleanOptionalAction,
        default=True,
        # BooleanOptionalAction appends "(default: True)" itself up to Python 3.12,
        # so the wording here does not repeat it.
        help="accept the previous round's tracked changes in the copied manuscript",
    )
    args = ap.parse_args()

    if args.src is not None:
        src = args.src if args.src.is_absolute() else REPO / args.src
    else:
        stages = stage_dirs()
        if not stages:
            ap.error("no stage with a manuscript found; pass --from explicitly")
        src = stages[-1]

    if args.dst is not None:
        dst = args.dst if args.dst.is_absolute() else REPO / args.dst
    else:
        dst = next_stage(src)
        if dst is None:
            ap.error(f"cannot tell what follows {src.name}; pass --to explicitly")

    if not src.is_dir():
        ap.error(f"{src} is not a directory")
    if dst.exists():
        ap.error(f"{dst} already exists; delete it or pass a different --to")

    # A manuscript that has not carried tracked changes yet becomes the annotated
    # one here.
    starting_revision = (src / "manuscript.tex").exists() and not (
        src / "manuscript_annotated.tex"
    ).exists()

    planned: list[tuple[Path, Path]] = []
    for name in SOURCE_FILES:
        if (src / name).exists():
            target = "manuscript_annotated.tex" if starting_revision and name == "manuscript.tex" else name
            planned.append((src / name, dst / target))
    # Every round of review comes with its own comments and its own cover letter, so
    # the templates in scripts/assets/ are laid down at each stage -- but never over
    # a file carried forward, which already holds the authors' formatting.
    carried = {d.name for _, d in planned}
    for asset in sorted(ASSETS.iterdir()):
        if asset.is_file() and asset.name not in carried:
            planned.append((asset, dst / asset.name))
    for name in SOURCE_DIRS:
        for p in sorted((src / name).rglob("*")):
            if p.is_file() and not p.name.startswith("."):
                planned.append((p, dst / p.relative_to(src)))

    # A first revision has nothing to accept: its markup is still to be written.
    src_annotated = src / "manuscript_annotated.tex"
    accept = args.accept_previous and not starting_revision and src_annotated.exists()
    accepted = len(TRACKED_CHANGE.findall(src_annotated.read_text())) if accept else 0

    print(f"{src.name} -> {dst.name}")
    for s, d in planned:
        print(f"  {d.relative_to(REPO)}")
    if accept:
        print(f"accepting {accepted} tracked-change macro(s) from {src.name}; \\linelabel anchors kept")
    if args.dry_run:
        print(f"({len(planned)} files, dry run -- nothing written)")
        return 0

    for s, d in planned:
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)

    annotated = dst / "manuscript_annotated.tex"
    if starting_revision:
        text = annotated.read_text()
        annotated.write_text(text.replace(r"\begin{document}", CHANGES_PREAMBLE + r"\begin{document}", 1))
    elif accepted:
        annotated.write_text(ps.flatten(annotated.read_text(), ACCEPT_MACROS))

    # A letter freshly laid down from scripts/assets/ still carries the marker where
    # its title block belongs. One carried forward from the previous round does not,
    # and must not be rewritten -- it holds the authors' own corrections by then.
    letter = dst / "response_to_reviewers.tex"
    if letter.exists() and METADATA_MARKER in (text := letter.read_text()):
        letter.write_text(text.replace(METADATA_MARKER, paper_metadata(annotated.read_text()), 1))
        print(f"took the title and authors from {annotated.name}")

    print(f"\nwrote {len(planned)} files into {dst.name}/. Next steps:")
    if accept:
        print(f"  1. mark up {dst.name}/manuscript_annotated.tex for this round -- the previous")
        print("     round's tracked changes have already been accepted")
    elif starting_revision:
        print(f"  1. mark up {dst.name}/manuscript_annotated.tex with \\added, \\replaced")
        print("     and \\deleted, and \\linelabel where the letter needs to point")
    else:
        print(f"  1. edit {dst.name}/manuscript_annotated.tex -- accept the previous round's")
        print("     tracked changes, then mark up the new round")
    print(f"  2. write {dst.name}/response_to_reviewers.tex for this round's comments")
    print("  3. uv run scripts/prepare_submission.py")
    print(f"  4. git add {dst.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
