#!/usr/bin/env python3
"""Open the next stage of the paper by copying the current one's sources forward.

A paper moves through draft/ -> manuscript/ -> revision_1/ -> revision_2/
and so on, one folder per round of review. Each folder is self-contained: the
manuscript, figs/ and the response letter all live there (the bibliography is
shared, at the repository root), so any stage can be rebuilt exactly as it was
sent.

Called with no arguments this advances one stage from the newest one, leaving it
frozen. Only sources are copied: the previous stage keeps its own deliverables and
its submission/ directory, and the clean manuscript is not copied at all, because
it is generated by scripts/make_submission.py rather than edited.

Usage:
    python3 scripts/new_revision.py                     # newest stage -> next
    python3 scripts/new_revision.py --dry-run
    python3 scripts/new_revision.py --from draft --to manuscript
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Copied forward: the sources the next stage is written from.
SOURCE_FILES = (
    "manuscript_annotated.tex",
    "manuscript.tex",
    "response_to_reviewers.tex",
)
SOURCE_DIRS = ("figs",)

STAGE_DRAFT = "draft"
STAGE_INITIAL = "manuscript"
REVISION_PREFIX = "revision_"


def has_manuscript(p: Path) -> bool:
    return any((p / n).exists() for n in ("manuscript_annotated.tex", "manuscript.tex"))


def revision_number(name: str) -> int | None:
    suffix = name[len(REVISION_PREFIX) :]
    return int(suffix) if name.startswith(REVISION_PREFIX) and suffix.isdigit() else None


def stage_dirs() -> list[Path]:
    """Every stage holding a manuscript, in the order the paper passes through them."""
    stages = [
        REPO / name
        for name in (STAGE_DRAFT, STAGE_INITIAL)
        if (REPO / name).is_dir() and has_manuscript(REPO / name)
    ]
    revisions = sorted(
        (n, p)
        for p in REPO.glob(f"{REVISION_PREFIX}*")
        if p.is_dir() and (n := revision_number(p.name)) is not None and has_manuscript(p)
    )
    return stages + [p for _, p in revisions]


def next_stage(src: Path) -> Path | None:
    """The folder that follows src in the pipeline."""
    if src.name == STAGE_DRAFT:
        return REPO / STAGE_INITIAL
    if src.name == STAGE_INITIAL:
        return REPO / f"{REVISION_PREFIX}1"
    n = revision_number(src.name)
    return REPO / f"{REVISION_PREFIX}{n + 1}" if n is not None else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--from", dest="src", type=Path, default=None, help="stage to copy from (default: newest)")
    ap.add_argument("--to", dest="dst", type=Path, default=None, help="stage to create (default: the next one)")
    ap.add_argument("--dry-run", action="store_true", help="list what would be copied")
    args = ap.parse_args()

    if args.src is not None:
        src = args.src if args.src.is_absolute() else REPO / args.src
    else:
        stages = stage_dirs()
        if not stages:
            ap.error("no stage with a manuscript found; pass --from explicitly")
        src = stages[-1]

    if args.dst is not None:
        dst = args.dst if args.dst.is_absolute() else REPO / args.dst
    else:
        dst = next_stage(src)
        if dst is None:
            ap.error(f"cannot tell what follows {src.name}; pass --to explicitly")

    if not src.is_dir():
        ap.error(f"{src} is not a directory")
    if dst.exists():
        ap.error(f"{dst} already exists; delete it or pass a different --to")

    planned: list[tuple[Path, Path]] = []
    for name in SOURCE_FILES:
        if (src / name).exists():
            planned.append((src / name, dst / name))
    for name in SOURCE_DIRS:
        for p in sorted((src / name).rglob("*")):
            if p.is_file() and not p.name.startswith("."):
                planned.append((p, dst / p.relative_to(src)))

    print(f"{src.name} -> {dst.name}")
    for s, d in planned:
        print(f"  {d.relative_to(REPO)}")
    if args.dry_run:
        print(f"({len(planned)} files, dry run -- nothing written)")
        return 0

    for s, d in planned:
        d.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(s, d)

    manuscript = next(
        (n for n in SOURCE_FILES if n.startswith("manuscript") and (dst / n).exists()),
        "manuscript.tex",
    )
    print(f"\ncopied {len(planned)} files. Next steps:")
    if dst.name == STAGE_INITIAL:
        print(f"  1. uv run scripts/make_submission.py")
        print(f"  2. upload {dst.name}/submission/ and git add {dst.name}")
        print("  (the target journal, reviewer suggestions and table of contents are")
        print("   dropped by the generator; delete them from the source too if you want")
        print("   your local previews to match what ships)")
        return 0

    print(f"  1. edit {dst.name}/{manuscript} -- accept the previous round's tracked")
    print("     changes, then mark up the new round")
    if manuscript == "manuscript.tex":
        print("     (rename it to manuscript_annotated.tex and load the changes package,")
        print("      since this round carries tracked changes)")
    print(f"  2. rewrite {dst.name}/response_to_reviewers.tex for the new comments")
    print(f"  3. uv run scripts/make_submission.py")
    print(f"  4. git add {dst.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
